### ISSUE TITLE
Brief Question About Internal Interface

### ISSUE THREAD

**Issue by alinebrito** [vpanarello/JAVA_FundamentalsAndUML#1]
Dear developer,

I am a master student at UFMG, Brazil. Currently, I am researching the use of internal interfaces by client projects. I mean, public interfaces for use only by internal modules (e.g., org.hamcrest.internal.ReflectiveTypeFinder). Your feedback will help to guide our research.

1. You used an internal interface in `Teste1` class of your project. Did you know that it is an internal interface of the Hamcrest library?
2. Are you aware that internal interfaces are unstable and may change without backward-compatibility?

Interface:  `org.hamcrest.internal.ArrayIterator`
File: [Teste1.java](https://github.com/vpanarello/JAVA_FundamentalsAndUML/blob/b77044715291ec59b61df3bd186c0309e5ca312a/20160510-Atividade03/ex03/ex03/Teste1.java)
Line: 5

**Comment by vpanarello** [comment]
Olá Aline Brito,

Ela foi importada pelo Ambiente Eclipse sem querer. Na verdade eu pretendia utilizar qualquer outra classe "Java.Util" relacionada a coleções. O eclipse importou essa interface e no final me esqueci de limpar o código.

Saudações,
Vagner

**Comment by alinebrito** [comment]
Oi Vagner, 

Obrigada pelo feedback!  Sua resposta vai ser muito útil pra minha pesquisa. 

Estou fechando a issue.
